# Default values for nerava-api
replicaCount: 3

image:
  repository: nerava-backend
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: ""
  annotations:
    # WAF and security annotations
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # CloudFront/WAF annotations (if using AWS)
    # alb.ingress.kubernetes.io/scheme: internet-facing
    # alb.ingress.kubernetes.io/target-type: ip
    # alb.ingress.kubernetes.io/load-balancer-attributes: routing.http2.enabled=true
  hosts:
    - host: nerava-api.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - nerava-api
        topologyKey: kubernetes.io/hostname

podDisruptionBudget:
  minAvailable: 1

probes:
  liveness:
    httpGet:
      path: /healthz
      port: 8000
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  
  readiness:
    httpGet:
      path: /readyz
      port: 8000
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

env:
  DATABASE_URL: "postgresql://nerava:nerava@postgres:5432/nerava"
  REDIS_URL: "redis://redis:6379/0"
  LOG_LEVEL: "INFO"
  REGION: "us-east-1"
  PRIMARY_REGION: "us-east-1"
  EVENTS_DRIVER: "redis"
  CACHE_TTL_WINDOWS: "60"
  RATE_LIMIT_PER_MINUTE: "120"
  ENABLE_SYNC_CREDIT: "false"

configMap:
  create: true
  data: {}

secrets:
  create: true
  data: {}

persistence:
  enabled: false
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    path: /metrics
