"""
Models package - organized by domain
"""
# Re-export all models for backward compatibility
from .user import User, UserPreferences
from .domain import (
    Zone,
    EnergyEvent,
    DomainMerchant,
    DriverWallet,
    NovaTransaction,
    DomainChargingSession,
    StripePayment,
)
from .vehicle import (
    VehicleAccount,
    VehicleToken,
    VehicleTelemetry,
)
from .while_you_charge import (
    Charger,
    Merchant,
    ChargerMerchant,
    MerchantPerk,
    MerchantBalance,
    MerchantBalanceLedger,
    MerchantOfferCode,
)
from .extra import (
    CreditLedger,
    IncentiveRule,
    UtilityEvent,
    Follow,
    RewardEvent,
    FollowerShare,
    CommunityPeriod,
    Challenge,
    Participation,
    FeatureFlag,
    MerchantIntelForecast,
    UtilityBehaviorSnapshot,
    RewardRoutingRun,
    CityImpactSnapshot,
    MobilityDevice,
    MerchantCreditLedger,
    ChargeVerificationLog,
    WalletInteropPartner,
    CoopPool,
    SdkTenantConfig,
    EnergyRepSnapshot,
    EnergyRepBackfill,
    OffsetBatch,
    FleetOrg,
    IotLink,
    GreenHourDeal,
    TenantModule,
    AiRewardSuggestion,
    FinanceOffer,
    GrowthCampaign,
    DualZoneSession,
)

__all__ = [
    # User models
    "User",
    "UserPreferences",
    # Domain models
    "Zone",
    "EnergyEvent",
    "DomainMerchant",
    "DriverWallet",
    "NovaTransaction",
    "DomainChargingSession",
    "StripePayment",
    # Vehicle models
    "VehicleAccount",
    "VehicleToken",
    "VehicleTelemetry",
    # While You Charge models
    "Charger",
    "Merchant",
    "ChargerMerchant",
    "MerchantPerk",
    "MerchantBalance",
    "MerchantBalanceLedger",
    "MerchantOfferCode",
    # Extra models
    "CreditLedger",
    "IncentiveRule",
    "UtilityEvent",
    "Follow",
    "RewardEvent",
    "FollowerShare",
    "CommunityPeriod",
    "Challenge",
    "Participation",
    "FeatureFlag",
    "MerchantIntelForecast",
    "UtilityBehaviorSnapshot",
    "RewardRoutingRun",
    "CityImpactSnapshot",
    "MobilityDevice",
    "MerchantCreditLedger",
    "ChargeVerificationLog",
    "WalletInteropPartner",
    "CoopPool",
    "SdkTenantConfig",
    "EnergyRepSnapshot",
    "EnergyRepBackfill",
    "OffsetBatch",
    "FleetOrg",
    "IotLink",
    "GreenHourDeal",
    "TenantModule",
    "AiRewardSuggestion",
    "FinanceOffer",
    "GrowthCampaign",
    "DualZoneSession",
]

