name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black mypy pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint
        run: |
          ruff check .
          black --check .
          mypy || true
      - name: Test
        run: |
          pytest -q || true
      - name: Run regression tests
        run: |
          pytest -q --disable-warnings --maxfail=1
