name: CI - Backend + Playwright Tests

on:
  push:
    branches: [ main, release/48h-sprint, sprint/ui-backend-sync ]
  pull_request:
    branches: [ main, release/48h-sprint ]

jobs:
  backend_ui:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Python dependencies
      run: |
        cd nerava-backend-v9
        pip install -r requirements.txt
        
    - name: Start backend server
      run: |
        cd nerava-backend-v9
        uvicorn app.main_simple:app --host 127.0.0.1 --port 8001 &
        sleep 10
        
    - name: Wait for backend health
      run: |
        for i in {1..30}; do
          if curl -f http://127.0.0.1:8001/health; then
            echo "Backend is ready"
            break
          fi
          echo "Waiting for backend... ($i/30)"
          sleep 2
        done
        
    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: ui-mobile/package-lock.json
        
    - name: Install Playwright
      run: |
        cd ui-mobile
        npm ci
        npx playwright install --with-deps
        
    - name: Run Playwright tests
      run: |
        cd ui-mobile
        npm run test:ui
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-results
        path: |
          ui-mobile/test-results/
          ui-mobile/playwright-report/
          ui-mobile/videos/
          ui-mobile/traces/
        retention-days: 30
        
    - name: Upload backend logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: backend-logs
        path: |
          nerava-backend-v9/*.log
        retention-days: 7